# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Moksha spellchecker"
mdf = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Moksha, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
mdf = "TRANSLATE: A spellchecker for Moksha, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.mdf"

[windows]
system_product_code = "{43F900B5-F0A0-43FF-B39C-B4284D84FA67}_is1"
legacy_product_codes = [
    { value = "7177C267-B0AE-4694-91E2-E9B95AA9822B", kind = "nsis" },
    { value = "1CBF7818-BC23-4DC2-8E5F-9761FACE6F2F", kind = "nsis" }
]

[package.speller]
name = "Moksha"
version = "0.1.1"

[package.grammar]
name = "Moksha"
version = "0.1.0"

[package.tts-text-proc]
name = "Moksha"
version = "0.1.0"

[package.hyphenator]
name = "Moksha"
version = "0.1.0"
